open-source-labs/Reactime

- src/app/components/Action.jsx
- src/app/containers/ActionContainer.jsx
- src/app/containers/MainContainer.jsx
- src/app/styles/abstracts/_variables.scss
- src/app/styles/base/_typography.scss
- src/app/styles/components/_actionComponent.scss
- src/app/styles/components/_buttons.scss
- src/app/styles/layout/_actionContainer.scss
- src/app/styles/main.scss
- src/app/styles/styles.scss
also set up scss scalable & modular css architecture
> applied style to action container

- package-lock.json
- package.json
- src/app/components/Action.jsx
- src/app/components/Slider.jsx
- src/app/containers/ActionContainer.jsx
- src/app/containers/MainContainer.jsx
- src/app/containers/StateContainer.jsx
- src/app/containers/TravelContainer.jsx
- src/app/styles/components/_jsonTree.scss
- src/app/styles/layout/_stateContainer.scss
- src/app/styles/main.scss
- src/app/styles/styles.scss
- src/extension/background.js
- src/extension/contentScript.js
backend => frontend: every new state change is recorded in the frontend (actionContainer/stateContainer)
frontend => backend: sends the target tree to backend
> connected backend with frontend

- src/app/containers/ActionContainer.jsx
- src/app/containers/ButtonsContainer.jsx
- src/app/containers/HeadContainer.jsx
- src/app/containers/MainContainer.jsx
- src/app/containers/StateContainer.jsx
- src/app/containers/TravelContainer.jsx
- src/extension/background.js
also lock and pause buttons now remember state upon closing devtools
> refactored stateful components into functional and added props validation

- package-lock.json
- src/app/components/MainSlider.jsx
- src/app/containers/MainContainer.jsx
- src/app/containers/TravelContainer.jsx
- src/extension/tree.js
also stops playing when user drags slider or click on forward, backward button
works well with persist,lock , pause function as well
> implmented play button

- package-lock.json
- package.json
- src/app/components/Dropdown.jsx
- src/app/containers/MainContainer.jsx
- src/app/containers/StateContainer.jsx
- src/app/containers/TravelContainer.jsx
- src/app/styles/layout/_travelContainer.scss
created a dropdown component
uses react-select npm package
changed travel container back to a stateful component bc it was unnecessary to bubble up certain states to main container
> added dropdown for selecting playback speed

- package.json
- src/app/actions/actions.js
- src/app/components/Action.jsx
- src/app/components/App.jsx
- src/app/components/Chart.jsx
- src/app/components/Dropdown.jsx
- src/app/components/MainSlider.jsx
- src/app/constants/actionTypes.js
- src/app/containers/ActionContainer.jsx
- src/app/containers/ButtonsContainer.jsx
- src/app/containers/MainContainer.jsx
- src/app/containers/TravelContainer.jsx
- src/app/reducers/mainReducer.js
- src/app/store.js
- src/extension/background.js
- src/extension/build/devtools.js
- src/extension/contentScript.js
removed eslint errors with chart.
fixed bug where importing didn't alert background script
> hooks and context

- src/app/__tests__/actionContainer.test.js
- src/app/__tests__/dropdown.test.js
> dropdown unit testing

- package/__mocks__/timeJump.js
- package/__tests__/index.test.js
- package/__tests__/linkFiber.test.js
- package/__tests__/timeJump.test.js
- package/index.js
- package/linkFiber.js
edge case, updated version of react
> package tests

- package/__mocks__/timeJump.js
- package/__tests__/index.test.js
- package/__tests__/linkFiber.test.js
- package/__tests__/timeJump.test.js
- package/index.js
- package/linkFiber.js
- package/package.json
no longer renames setState.
adds a variable to keep track.
also package updated
> changed the way changeSetState operates

- src/app/components/SwitchApp.jsx
- src/app/containers/HeadContainer.jsx
- src/app/containers/MainContainer.jsx
- src/app/reducers/mainReducer.js
- src/app/styles/layout/_headContainer.scss
- src/extension/background.js
1. Tab dropdown shows title of each tab
2. Changing state of application changes tab of dev tool to corresponding one
- Will workon styling and other stuff more
> Bryan sierra/tabs

- package/astParser.js
- package/linkFiber.js
- package/package-lock.json
- src/extension/contentScript.js
AST restructured to target elementType funcs for hooks
> AST implementation fixed using elementType prop

- .gitignore
- src/app/__tests__/Chart.test.jsx
- src/app/__tests__/mainReducer.test.jsx
- src/app/__tests__/switchState.test.jsx
Added placeholders and excluded tests that need major refactoring for new features
> Jest v1 testing

- readme.md
Fixes #153.
Replaced AWS link with gh-page link.
> Update calculator example link

- package-lock.json
- src/app/components/PerfView.tsx
fix D3 NaN error on sites w no render data
PerfView.tsx added error checking for missing data before zooming + ESLint auto fixes
Run on unsupported site (Codesmith.io, which uses redux for example) and switch to Performance tab. Make sure no errors appear in Chrome background console.
> fix D3 NaN error on sites w no render data

- package-lock.json
- src/app/components/PerfView.tsx
- src/app/styles/components/d3graph.css
- src/app/styles/layout/_stateContainer.scss
> Font tweaks in PerfView

- README.md
- Reactime 8.0 launch
Co-authored-by: kev-ngo <kevinngo.cal@gmail.com>
Co-authored-by: CourageWolf <marchofthepenguins1@gmail.com>
Co-authored-by: C-STYR <colestyron@gmail.com>
Co-authored-by: demircaner <canerdemir62@gmail.com>
> Updated README.md with Reactime 8.0 Updates

- DeveloperREADME.md
- README.md
- package.json
- src/README.md
- src/extension/build/manifest.json
Update Webpack Node options for Node@18.12.1
Add script "devlegacy" && "buildlegacy" for Node@16.16.0
> Add compatibility for Nodev18.12.1

- README.md
Update Alternative Developer Install Instruction
> Update Alternative Developer Install  Instruction

- CONTRIBUTING.md
- README.md
- src/README.md
Add contributing documentation
> Add CONTRIBUTING.md

- www/package.json
- www/src/env/schema.mjs
- www/src/pages/api/examples.ts
Removed example router, added linting dependency
> Removed Example Router

- package.json
- src/app/components/StateRoute/AxMap/AxMap.tsx
- src/app/components/StateRoute/AxMap/ToolTipDataDisplay.tsx
- src/app/components/StateRoute/ComponentMap/ComponentMap.tsx
- src/app/slices/mainSlice.ts
- src/backend/controllers/timeJump.ts
- src/extension/background.js
- src/extension/build/manifest.json
Removed console.logs, removed commented out code, and added v24 contributors to manifest.json
> Refactoring for v24 launch

- src/app/components/StateRoute/AxMap/axLegend.tsx
- Updated medium article in READme to team 24 article
- Included v24 members in READme
- Committed latest version of reactime website repo
> Update READme and reactime website repo

- README.md
Updated the readme to include v24 contributors, the relevant medium article, and the accessibility tab in the what's new section
> fix: updated readme for v24 updates
